apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      terminationGracePeriodSeconds: 4
      containers:
      - name: server
        image: eu.gcr.io/apigee-quest-v2/frontend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SHOW_HIPSTER_KIDS
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  labels:
    version: v2
spec:
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      terminationGracePeriodSeconds: 4
      containers:
      - name: server
        image: eu.gcr.io/apigee-quest-v2/frontend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SHOW_HIPSTER_KIDS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: frontend